<?php

/** @noinspection PhpUndefinedVariableInspection */
/**
 * Do not edit this file directly.  You can copy this file to your theme directory
 * in /your-theme/woocommerce-pay-per-post/shortcode-purchased-datatables.php
 * The $purchased variable is a WP Posts Object of purchased posts.
 */