<?php  /** @noinspection PhpUndefinedVariableInspection */ ?>

<?php
/**
 * Do not edit this file directly.  You can copy this file to your theme directory
 * in woocommerce-pay-per-post/woocommerce-order-receipt.php
 * The $purchased variable is a WP Posts Object of purchased posts.
 */
?>
<div class="ppp-purchased-content"><strong><?php echo apply_filters( 'wc_pay_per_post_purchased_content_title', esc_html__( 'Access Your Purchased Content', 'wc_pay_per_post' ) ); ?></strong><br>
	<ul class="ppp-purchased-content__list">
		<?php foreach ( $purchased as $item ): ?>
			<li><a href="<?php echo $item['post_url']; ?>" target="_blank"><?php echo $item['post_title']; ?></a></li>
		<?php endforeach; ?>
	</ul>
</div>