<?php  /** @noinspection PhpUndefinedVariableInspection */ ?>

<?php
/**
 * Do not edit this file directly.  You can copy this file to your theme directory
 * in woocommerce-pay-per-post/woocommerce-order-receipt.php
 * The $purchased variable is a WP Posts Object of purchased posts.
 */
/** @noinspection PhpUndefinedFunctionInspection */
$current_language = pll_default_language();
?>
<div class="ppp-purchased-content"><strong><?php apply_filters( 'wc_pay_per_post_purchased_content_title', esc_html__( 'Access Your Purchased Content', 'wc_pay_per_post' ) ); ?></strong><br>
	<ul class="ppp-purchased-content__list">

		<?php foreach ( $purchased as $post ) : /** @noinspection PhpUndefinedFunctionInspection */
			$languages = pll_get_post_translations($post['post_id']); ?>
            <li>
                <strong><a href="<?php echo esc_url( get_permalink( $languages[$current_language] ) ); ?>">[<?php echo $current_language; ?>] <?php echo esc_html( get_the_title($languages[$current_language]) ); ?></a></strong><br>
				<?php if($languages > 1): ?>
					<?php apply_filters( 'wc_pay_per_post_languages_title', esc_html__( 'Additional Languages', 'wc_pay_per_post' ) ) ?>
                    <ul>
						<?php foreach($languages as $language => $post_id): if($language === $current_language): continue; endif; ?>
                            <li><a href="<?php echo esc_url( get_permalink( $post_id ) ); ?>">[<?php echo $language; ?>] <?php echo esc_html( get_the_title($post_id) ); ?></a></li>
						<?php endforeach; ?>
                    </ul>
				<?php endif;  ?>
            </li>
		<?php endforeach; ?>
	</ul>
</div>